stages:
  - stage: prepare_deployment
    displayName: "Prepare deployment"
    jobs:
      - job: deploy_job
        displayName: "Deploy"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.8"
            displayName: "Use Python 3.8"
          - script: |
              ls $(Build.SourcesDirectory)
            displayName: "List Sources Directory"
          - task: AzureKeyVault@1
            displayName: "Connect to Azure Keyvault"
            inputs:
              azureSubscription: 'MambaDevSVC'
              KeyVaultName: 'MambaDevKV'
              SecretsFilter: '*'
              RunAsPreJob: true
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens'
            inputs:
              targetFiles: |
                $(Build.SourcesDirectory)/ansible/inv

          - task: PrepareAnsibleRuntime@0
            displayName: "Prepare Ansible"
            inputs:
              ansibleConfigFilePath: $(Build.SourcesDirectory)/ansible/
              
          - task: Ansible@0
            displayName: "Run Ansible"
            inputs:
              ansibleInterface: "agentMachine"
              inventoriesAgentMachine: "file"
              playbookPathOnAgentMachine: $(Build.SourcesDirectory)/ansible/remote_playbook.yml
              inventoryFileOnAgentMachine: $(Build.SourcesDirectory)/ansible/inv
              args: ""

  - stage: build
    displayName: "Build wheel file"
    dependsOn:
      - prepare_deployment
    condition: succeeded()
    jobs:
      - job: build_wheel
        displayName: "Build wheel file"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"