stages:
  - stage: prepare_deployment
    displayName: "Prepare deployment"
    jobs:
      - job: deploy_job
        displayName: "Deploy"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.8"
            displayName: "Use Python 3.8"
          - script: |
              ls $(Agent.BuildDirectory)
            displayName: "List Agent Build Directory"
          - task: AzureKeyVault@1
            displayName: "Connect to Azure Keyvault"
            inputs:
              azureSubscription: 'MambaDevSVC'
              KeyVaultName: 'MambaDevKV'
              SecretsFilter: '*'
              RunAsPreJob: true
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens'
            inputs:
              targetFiles: |
                $(Agent.BuildDirectory)/ansible/inv

  - stage: build
    displayName: "Build wheel file"
    dependsOn:
      - prepare_deployment
    condition: succeeded()
    jobs:
      - job: build_wheel
        displayName: "Build wheel file"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"