---
- hosts: dev

  pre_tasks:
    - name: Include vars
      include_vars:
        ../vars/default_vars.yml

  tasks:

  - debug: msg={{ ProjectRoot }}
    name: "Show project root"

  - name: Create temp staging directory
    import_role:
      name: role-create-tmp
