---
- hosts: dev

  pre_tasks:
    - name: Include vars
      include_vars:
        ../vars/default_vars.yml

  tasks:

  - name: "Generate random string for directory"
    shell: "echo $RANDOM"
    register: "_rand"

  - debug: msg={{ ProjectRoot }}/{{ _rand }}

  - debug: msg={{ ProjectRoot }}
    name: "Show project root"

  - name: "Generatex "
    shell: "echo hello"
    register: "_x"

  - debug: msg={{ ProjectRoot }}/{{ _x }}