---
- hosts: dev

  pre_tasks:
    - name: Include vars
      include_vars:
        ../vars/default_vars.yml

  tasks:
  - block:

     - name: Create temp staging directory
       import_role:
         name: ../roles/role-create-tmp

     - debug: msg={{ staging_dir.path }}
       name: "Temporary staging directory path"

     - debug: msg={{ artifacts_to_be_deployed }}
       name: "Artifacts"

#    always:
#
#    - name: Clean temp staging directory
#      file:
#        state: absent
#        path: "{{ staging_dir.path }}"
